export {default as Home} from './Home/Home'
export {default as Weather} from './Weather/Weather'
export {default as Contact} from './Contact/Contact'
export {default as Projects} from './Projects/Projects'
export {default as Terms} from './Terms_of_service/Terms'
export {default as Privacy} from './Privacy_policy/Privacy'